package Config;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

public class CommonMethods {
    protected static String timestamp_hh_mm_ss;
    /**
     * generateTimestamp_hh_mm_ss() method to generate timestamp in HH_MM_SS format
     * static block initializes the timestamp_hh_mm_ss variable with the value generated by generateTimestamp_hh_mm_ss() method
     * getTimestamp_hh_mm_ss() method to access the value of the timestamp_hh_mm_ss
     */
    private static String generateTimestamp_hh_mm_ss() {
        LocalTime currentTime = LocalTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH_mm_ss");
        return currentTime.format(formatter);
    }

    static {
         timestamp_hh_mm_ss = generateTimestamp_hh_mm_ss();
    }

    public static String getTimestamp_hh_mm_ss() {
        return timestamp_hh_mm_ss;
    }


}
